import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { lexend_deca, space_mono } from './fonts'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${lexend_deca.variable} ${space_mono.variable}`}>{children}</body>
    </html>
  )
}
