import type { Metadata } from 'next'
import { lexend_deca, space_mono } from './fonts'
import './globals.css'

export const metadata: Metadata = {
  title: 'Scoot',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="overflow-x-hidden">
      <body className={`${lexend_deca.variable} ${space_mono.variable} overflow-x-hidden`}>
        {children}
      </body>
    </html>
  )
}
